/* Fields rendered on each entity box, plus inline field comments.
 * Types are resolved from the live schema, so only names are declared here.
 * A name that no longer exists in the schema is a build error.
 *
 * Prefix an entry with "+" to render an embedded container (single subdocument
 * or nested-path group) as one box line instead of expanding its children. */

const SHOW = {
  User: ['_id', 'email', 'passwordHash', 'firstName', 'lastName', 'phone', 'role', 'permissions', 'accountStatus', 'blocked', 'vip', 'active', 'archivedAt'],
  Role: ['_id', 'name', 'label', 'permissions', 'isSystem', 'revision'],
  Technician: ['_id', 'user', 'name', 'phone', 'availabilityStatus', '+location', 'rating', 'ratingCount', 'archivedAt'],
  Secretary: ['_id', 'user', 'phone', 'extension', 'shift'],
  AuthSession: ['_id', 'sessionId', 'userId', 'revoked', 'lastActivityAt', 'createdAt'],
  TrustedDevice: ['_id', 'userId', 'tokenHash', 'label', 'passwordChangedAt', 'expiresAt', 'revokedAt'],
  LoginHistory: ['_id', 'userId', 'ip', 'country', 'deviceType', 'isNewDevice', 'suspicious'],
  FailedLoginAttempt: ['_id', 'userId', 'email', 'ip', 'count', 'lastAttemptAt', 'lockedUntil'],

  Brand: ['_id', 'name', 'description', 'active'],
  Category: ['_id', 'name', 'description', 'active'],
  ServiceCategory: ['_id', 'name', 'slug', 'unitTypes', 'warrantyPolicy', 'order', 'active', 'archivedAt'],
  CoreService: ['_id', 'name', 'slug', 'category', 'basePrice', 'durationMinutes', 'hpPricing', 'warrantyPolicy', 'active', 'archivedAt'],
  RepairService: ['_id', 'name', 'slug', 'applianceType', 'initialPrice', 'basePrice', 'laborPerHour', 'warrantyDays', 'allowTechnicianPricing'],
  Service: ['_id', 'name', 'slug', 'category', 'basePrice', 'active'],
  HVACProduct: ['_id', 'modelLine', 'brand', 'category', 'type', 'variants', 'salesChannel', 'active', 'archivedAt'],
  Inventory: ['_id', 'modelLine', 'sku', 'barcode', 'brand', 'category', 'capacity', 'quantity', 'minStockLevel', 'status', 'active', 'archivedAt'],

  BookingService: ['_id', 'bookingReference', 'customerId', 'serviceType', 'serviceModel', 'serviceId', 'services', 'status', 'paymentStatus', 'bookingDate', 'startTime', 'endTime', 'technicianId', 'assignmentId', '+location', 'totalInitialCost', 'totalFinalCost', '+warranty', 'customerRating', 'statusHistory', '+slaTracking'],
  Assignment: ['_id', 'bookingId', 'technicianId', 'projectId', 'serviceItemId', 'status', 'priority', 'acceptanceDeadline', 'bookingDate', 'startTime', 'endTime', 'arrivalProofUrl', 'equipmentCheckedOut', 'equipmentReturned'],
  ServiceReport: ['_id', 'bookingId', 'serviceItemId', 'assignmentId', 'technicianId', 'findings', 'partsReplaced', 'laborHours', 'actualLaborCost', 'customerSignature', 'status', 'approvedBy'],
  UnitAssistanceRequest: ['_id', 'customerId', 'serviceId', 'existingBookingId', 'bookingId', 'status', '+quote', 'resolvedBy'],
  RelocationRequest: ['_id', 'customerId', 'serviceId', 'assetId', 'bookingId', 'scope', 'status', '+quote'],  TechnicianSchedule: ['_id', 'technicianId', 'workingDays', 'nonWorkingWeekdays', 'restDates'],
  NonWorkingDay: ['_id', 'date', 'service', 'reason', 'active'],

  Tool: ['_id', 'itemName', 'itemType', 'type', 'inventoryClass', 'category', 'assetCode', 'barcode', 'quantity', 'reservedQuantity', 'minStockLevel', 'status', 'active', 'archivedAt'],
  ToolAssignment: ['_id', 'toolId', 'technicianId', 'toolName', 'quantity', 'status', 'assignedDate', 'returnedDate'],
  EquipmentAssignment: ['_id', 'equipmentId', 'technicianId', 'projectId', 'projectIds', 'workOrderId', 'workOrderIds', 'bookingId', 'dailyKitId', 'serviceItemId', 'workDate', 'status', 'quantity', 'expectedReturnAt', 'resolutionState'],
  EquipmentUsageLog: ['_id', 'technicianId', 'equipmentId', 'equipmentName', 'date', 'notes'],
  DailyKit: ['_id', 'technicianId', 'workDate', 'status', 'items', 'assignmentIds', 'bookingIds', 'orderIds', 'projectIds', 'workOrderIds', 'dailyAssignmentIds', 'hasDelta'],
  ServiceToolUsage: ['_id', 'toolItemId', 'bookingId', 'orderId', 'assignmentId', 'projectId', 'workOrderId', 'serviceItemId', 'quantityUsed', 'deductedFromInventory', 'lifecycleStatus'],
  StockReservation: ['_id', 'toolId', 'bookingId', 'serviceItemId', 'quantity', 'status', 'stockTreatment'],
  StockAdjustment: ['_id', 'toolId', 'type', 'reason', 'quantityBefore', 'quantityAfter', 'delta', 'adjustedBy', 'referenceId'],
  PartsRequest: ['_id', 'bookingId', 'projectId', 'serviceItemId', 'customerId', 'technicianId', 'status', 'items', 'resumeStatus'],

  Project: ['_id', 'bookingId', 'customerId', 'status', 'projectPhase', 'isLargeScale', 'quantity', 'totalUnits', 'assignedTechnicians', '+schedulePlan', '+quotationReview', '+payment', 'leadTechnicianId'],
  WorkOrder: ['_id', 'projectId', 'bookingId', 'workOrderNumber', 'title', 'status', 'planningStatus', 'priority', 'units', 'resourceRequirements', 'dependencies', 'assignedTechnicians'],
  DailyAssignment: ['_id', 'projectId', 'workOrderId', 'technicianId', 'date', 'status'],
  ProjectMaterial: ['_id', 'projectId', 'workOrderId', 'type', 'scope', 'status', 'source', 'sourceId', 'assignedToTechnicianId', 'quantity'],
  ProjectIssue: ['_id', 'projectId', 'workOrderId', 'category', 'status', '+reportedBy', 'resolvedBy'],
  ProjectResourcePurchase: ['_id', 'projectId', 'toolId', 'resourceId', 'status', 'orderedQuantity', 'receivedQuantity', 'receipts', 'createdBy'],
  ProjectWorkSubmission: ['_id', 'projectId', 'technicianId', 'submittedByUserId', 'clientSubmissionId', 'workOrders', 'consumables'],

  AirconCart: ['_id', 'userId', 'items'],
  Order: ['_id', 'orderReference', 'userId', 'salesChannel', 'fulfillmentType', 'status', 'items', 'subtotal', 'discount', 'total', 'technicianId', 'bookingId', 'paymentId', 'paymentStatus'],
  WalkInSale: ['_id', 'invoiceNumber', 'customerName', 'items', 'subtotal', 'discount', 'totalAmount', 'amountPaid', 'paymentMethod', 'status', 'processedBy'],
  Purchase: ['_id', 'userId', 'items', 'subtotal', 'tax', 'total', 'purchaseDate', 'status'],

  Payment: ['_id', 'bookingId', 'orderId', 'projectId', 'workOrderId', 'method', 'gateway', 'type', 'amount', 'status', 'submittedAt', 'proofUrl', 'collectedBy', 'verifiedBy', 'payrollDeductionId'],
  Payroll: ['_id', 'employee', 'employeeRole', 'periodStart', 'periodEnd', 'basicPay', 'overtimePay', 'allowances', 'deductions', 'grossPay', 'netPay', '+attendanceSummary', 'compensationRecord', 'status'],
  EmployeeCompensation: ['_id', 'employee', 'payType', 'baseRate', 'overtimeRate', 'effectiveFrom', 'effectiveTo', 'active'],
  Expense: ['_id', 'technicianId', 'technicianName', 'type', 'amount', 'expenseDate', 'bookingId', 'projectId', 'workOrderId', 'status', 'approvedBy'],

  CustomerAsset: ['_id', 'customerId', 'assetKey', 'originType', 'originId', '+equipment', 'status', 'lastServiceDate', 'maintenanceIntervalDays', 'latestScheduleId', 'serviceHistory'],
  MaintenanceSchedule: ['_id', 'assetId', 'customerId', 'cycleNumber', 'cycleKey', 'dueDate', 'status', 'sourceCompletionType', 'sourceCompletionId', 'bookingId', 'completedByBookingId', '+outreach'],
  WarrantyClaim: ['_id', 'customerId', 'sourceType', 'sourceId', 'coverageId', 'coverageSnapshot', 'claimType', 'status', 'requestedRemedy', 'assignedTechnicianId', 'active'],
  ProductReturn: ['_id', 'rmaNumber', 'sourceType', 'sourceId', 'customerId', 'productId', 'itemIndex', 'bookingId', 'workOrderId', 'status', '+inspection', '+resolution'],
  ProductRefund: ['_id', 'returnId', 'originalPaymentId', 'status', 'method', 'amount', 'approvedBy', 'processedBy'],
  ProductReturnMovement: ['_id', 'returnId', 'productId', 'type', 'actorId'],
  Rating: ['_id', 'customerId', 'targetType', 'targetId', 'score', 'comment', 'moderationStatus'],

  TechnicianAttendance: ['_id', 'technicianId', 'userId', 'date', 'status', 'checkInTime', 'checkOutTime', 'method', 'securityVersion', 'checkInEvidence', 'noExpensesTodayConfirmed', 'updatedBy'],  SecretaryAttendance: ['_id', 'userId', 'date', 'status', 'checkInTime', 'checkOutTime', 'method', 'qrVerified', 'updatedBy'],
  LeaveRequest: ['_id', 'technicianId', '+technician', 'startDate', 'endDate', 'reason', 'status', 'reviewedBy'],

  SiteSetting: ['_id', 'key', 'value'],
  ActivityLog: ['_id', 'actor', 'target', 'entityType', 'entityId', 'action', 'category', 'outcome', 'riskLevel', 'ip'],
  Notification: ['_id', 'userId', 'role', 'type', 'title', 'message', 'referenceId', 'referenceModel', 'link', 'read', 'priority'],
  EmailOutbox: ['_id', 'recipientHash', 'source', 'status', 'attempts', 'nextAttemptAt', 'expiresAt'],
  EmailDeliveryLog: ['_id', 'recipient', 'provider', 'subject', 'status', 'messageId', 'createdAt'],
  OperationLock: ['_id', 'owner', 'acquiredAt', 'expiresAt'],
};

/* "<Model>.<path>" -> note rendered next to the field in the entity box.
 * For embedded containers the key omits the "+" SHOW prefix. */
const FIELD_COMMENT = {
  'User.role': 'STRING join to Role.name',
  'User.passwordHash': 'bcrypt; never selected by default',
  'User.permissions': 'empty falls back to Role.permissions',
  'Role.name': 'join key from User.role',
  'Technician.user': 'UNIQUE + SPARSE, so 1:0..1 with User',
  'Technician.availabilityStatus': 'derived cache of availability.js',
  'Technician.location': 'live GeoJSON GPS from the field client',
  'BookingService.serviceModel': 'refPath discriminator: CoreService|RepairService',
  'BookingService.serviceId': 'refPath resolves via serviceModel',
  'BookingService.services': 'embedded work items, each with its OWN status',
  'BookingService.status': 'aggregate status, a compatibility summary',
  'BookingService.paymentStatus': '10 values, mirrors Payment.status',
  'BookingService.startTime': 'STRING ("540" or "09:00"); 3 parsers exist',
  'BookingService.warranty': 'legacy scalars plus per-item coverages[] (Mixed)',
  'BookingService.assignmentId': 'nullable; nulled when an assignment expires',
  'BookingService.statusHistory': 'audit trail; changedBy uses a refPath',
  'BookingService.slaTracking': 'response/resolution targets and breach flags',
  'Assignment.serviceItemId': 'BARE ObjectId into BookingService.services[]',
  'Assignment.acceptanceDeadline': 'defaults to now + 30 minutes',
  'ServiceReport.serviceItemId': 'BARE ObjectId into services[]',
  'ServiceReport.actualLaborCost': 'internal direct labour, NOT customer labourCost',
  'UnitAssistanceRequest.existingBookingId': 'resolved on an OPEN booking instead of converting',
  'TechnicianSchedule.technicianId': 'UNIQUE + SPARSE, exactly one schedule per technician',
  'NonWorkingDay.service': 'refs LEGACY Service, not CoreService/RepairService',
  'HVACProduct.variants': 'embedded subdocs, each with its OWN quantity and sku',
  'Inventory.quantity': 'no reservedQuantity field exists here',
  'Tool.reservedQuantity': 'denormalised; recomputed from ProjectMaterial',
  'Tool.category': 'free-text String, NOT a ref to Category',
  'EquipmentAssignment.equipmentId': 'the Tool being issued (name is misleading)',
  'EquipmentAssignment.projectId': 'conditionally required when no bookingId/dailyKitId',
  'EquipmentAssignment.workOrderId': 'legacy scalar; the arrays are authoritative',
  'EquipmentAssignment.serviceItemId': 'BARE ObjectId into services[]',
  'EquipmentUsageLog.equipmentId': 'free-text log, no quantity so it cannot move stock',
  'DailyKit.workDate': 'UNIQUE (technicianId, workDate)',
  'DailyKit.items.custodyAssignmentIds': 'prevents double-issuing already-handed-over equipment',
  'ServiceToolUsage.toolItemId': 'inventoryItemId is a deprecated alias',
  'StockReservation.stockTreatment': 'deducted = hard -qty; soft_hold = -reservedQuantity',
  'StockAdjustment.referenceId': 'refs BookingService, not a generic entity',
  'Project.bookingId': 'required; BookingService has NO projectId back-ref',
  'Project.schedulePlan': 'generated/preview/ready/blocked/confirmed',
  'Project.quotationReview': 'pending | approved | rejected',
  'Project.payment': 'project-scoped payment mirror',
  'ProjectMaterial.sourceId': 'BARE ObjectId into Tool when source=inventory',
  'ProjectResourcePurchase.resourceId': 'BARE ObjectId into Project.planningDraft.resources[]',
  'AirconCart.items': 'lines are PULLED on checkout; no orderId is kept',
  'Order.items': 'inventoryId may hold an HVACProduct.variants._id',
  'Order.salesChannel': 'online | walk_in | phone | admin',
  'Order.fulfillmentType': 'POS carry_out is coerced to customer_pickup',
  'Order.bookingId': 'inverse of BookingService.sourceOrderId',
  'Order.paymentId': 'inverse of Payment.orderId',
  'WalkInSale.items': 'toolId may hold an HVACProduct.variants._id',
  'WalkInSale.processedBy': 'the POS operator; there is no Payment document',
  'Payment.bookingId': 'one of FOUR nullable parent refs, no discriminator',
  'Payment.method': 'customer channel (gcash|maya|card|cod|cash|bank|paymongo|other)',
  'Payment.gateway': 'provider; EXCLUDES cash and card',
  'Payment.proofUrl': 'often a session-gated ROUTE, not resolvable data',
  'Payment.payrollDeductionId': 'the only Payment to Payroll link',
  'Payroll.employee': 'refs User, NOT Technician or Secretary',
  'Payroll.attendanceSummary': 'frozen counts, NO join back to attendance rows',
  'Payroll.compensationRecord': 'unindexed, non-unique, no reverse ref',
  'Expense.projectId': 'the only transactional model reaching Project',
  'CustomerAsset.originId': 'BARE ObjectId plus originType discriminator',
  'CustomerAsset.equipment': 'denormalised unit description, strings not refs',
  'CustomerAsset.latestScheduleId': 'cyclic FK with MaintenanceSchedule.assetId',
  'CustomerAsset.serviceHistory': 'append-only trail, each row refs its booking',
  'MaintenanceSchedule.assetId': 'cyclic FK with CustomerAsset.latestScheduleId',
  'MaintenanceSchedule.sourceCompletionId': 'BARE ObjectId, no ref',
  'MaintenanceSchedule.status': 'persisted value can disagree with the derived one',
  'MaintenanceSchedule.bookingId': 'PARTIAL UNIQUE where type=objectId',
  'MaintenanceSchedule.outreach': 'customer contact state machine',
  'WarrantyClaim.sourceId': 'BARE ObjectId plus sourceType discriminator',
  'WarrantyClaim.coverageId': 'STRING into a Mixed[] array; not validated',
  'WarrantyClaim.coverageSnapshot': 'terms frozen at filing time',
  'ProductReturn.sourceId': 'BARE ObjectId plus sourceType discriminator',
  'ProductReturn.productId': 'BARE ObjectId: Inventory OR HVACProduct variant',
  'ProductReturn.inspection': 'physical inspection outcome and disposition',
  'ProductReturn.resolution': 'refund or replacement decision; links the refund',
  'ProductRefund.returnId': 'UNIQUE, so at most one refund per return',
  'ProductReturnMovement.productId': 'BARE ObjectId, no discriminator column',
  'Rating.targetId': 'BARE ObjectId; targetType has NO refPath',
  'TechnicianAttendance.userId': 'optional; the payroll join runs through this',
  'TechnicianAttendance.checkInEvidence': 'GPS, geofence, trusted-device and QR proof',
  'SecretaryAttendance.userId': 'attendance subject is User, NOT Secretary',
  'LeaveRequest.technicianId': 'required but NOT indexed',
  'LeaveRequest.technician': 'name/email/phone snapshot, not a ref',
  'ActivityLog.entityId': 'BARE ObjectId; `target` is always a User ref',
  'ActivityLog.target': 'always refs User, NOT the acted-on entity',
  'Notification.referenceId': 'BARE ObjectId; referenceModel has no refPath',
  'EmailOutbox.recipientHash': 'SHA-256; payload is AES-256-GCM encrypted',
  'EmailDeliveryLog.recipient': 'PLAINTEXT email, indexed, 90 day TTL',
  'EmailDeliveryLog.createdAt': 'TTL: expireAfterSeconds 90',
  'EmailOutbox.expiresAt': 'TTL: expireAfterSeconds 0',
  'TrustedDevice.expiresAt': 'TTL index',
  'OperationLock._id': 'the lock name, e.g. booking-capacity:2026-10-09',
  'Purchase.items': 'productId refs the NON-EXISTENT model Product',
};

module.exports = { SHOW, FIELD_COMMENT };
